name: 'GitHub Pages CI/CD'

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+*']

jobs:
  deploy:
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: zofrex/mirror-branch@v1.0.0
      with:
        target-branch: gh-pages
